# Generated by Selenium IDE
import pytest
import allure
import time
import json



@pytest.mark.usefixtures("browser")
@allure.feature("medicarecoveragehelpline quote")
@allure.story('medicarecoveragehelp line quote')
@allure.severity('critical')
class TestShoppingflow ():

    @allure.step("open medicarecoveragehelpline site and redirect to medicare healthinsure site")
    def test_shoppingflow(self,browser):
        browser.get("https://qa.medicarecoveragehelpline.com/")
        browser.find_element_by_xpath("//button[@type='submit']").click()
        browser.find_element_by_id("zip").click()
        browser.find_element_by_id("zip").clear()
        browser.find_element_by_id("zip").send_keys("60601")
        browser.find_element_by_xpath(
            "//div[@id='__next']/div[2]/div/form/div/div/div/div/div/div/div[2]/button").click()
        browser.find_element_by_id("firstName").click()
        browser.find_element_by_id("firstName").clear()
        browser.find_element_by_id("firstName").send_keys("Test")
        browser.find_element_by_id("lastName").click()
        browser.find_element_by_id("lastName").clear()
        browser.find_element_by_id("lastName").send_keys("last")
        browser.find_element_by_xpath(
            "//div[@id='__next']/div[2]/div/form/div/div/div/div/div/div/div[2]/button").click()
        browser.find_element_by_id("email").click()
        browser.find_element_by_id("email").clear()
        browser.find_element_by_id("email").send_keys("testlast@gmail.com")
        browser.find_element_by_xpath(
            "//div[@id='__next']/div[2]/div/form/div/div/div/div/div/div/div[2]/button").click()
        browser.find_element_by_id("phone").click()
        browser.find_element_by_id("phone").clear()
        browser.find_element_by_id("phone").send_keys("(344) 334-4334")
        browser.find_element_by_xpath(
            "//div[@id='__next']/div[2]/div/form/div/div/div/div/div/div/div[2]/button").click()
        # browser.implicitly_wait(1)
        # browser.find_element_by_xpath("//div[@id='__next']/div[4]/div/div/div[3]/button[2]/div/p").click()
        # browser.get("https://staging.medicare.healthinsurance.com/quote")
        browser.quit()


if __name__ == '__main__':
    pytest.main(['-s','-vv','test_sanity.py' ,'-q', '--alluredir', '../report/xml'])
