# Generated by Selenium IDE
import pytest
import allure
import time
from selenium import webdriver
from selenium.webdriver.common.by import By
import pandas as pd

filename = '../../data/comparePlanDetails.csv'
df_obj = pd.read_csv(filename)
df_obj.head()


class TestMedicarePlanDetail():
    def setup_method(self, method):
        # self.driver = webdriver.Remote(command_executor='http://localhost:4444/wd/hub', desired_capabilities=DesiredCapabilities.FIREFOX)
        # self.driver = webdriver.Chrome(executable_path='../../driver/chromedriver')
        # self.driver = webdriver.Firefox()
        self.driver = webdriver.Chrome()
        print("start the browser...")
        self.vars = {}

    def teardown_method(self, method):
        self.driver.quit()

    def test_medicare(self):
        # Step # | name | target | value

        @allure.step(title='go to home')
        # 1 | open | / |
        self.driver.get("https://sunmaker.medicare.healthinsurance.com")
        # 2 | setWindowSize | 1440x900 |
        self.driver.set_window_size(1440, 900)
        # 3 | click | linkText=Census |
        # self.driver.find_element(By.LINK_TEXT, "Census").click()
        # 4 | click | name=census.location.zip |
        self.driver.implicitly_wait(60)
        self.driver.find_element(By.NAME, "census.location.zip").click()
        # 5 | type | name=census.location.zip | 30301
        self.driver.find_element(By.NAME, "census.location.zip").send_keys("30301")
        # 6 | click | xpath=//div[@id='__next']/div[2]/div/div/div[2]/div |
        self.driver.implicitly_wait(60)
        time.sleep(5)


        @allure.step(title='open quote page')
        self.driver.find_element(By.XPATH, "//div[@id=\'__next\']/div[2]/div/div/div[2]/div").click()
        # 7 | click | xpath=//div[@id='__next']/div[2]/div/div/div[2]/div/div/form/div/div[2]/button |
        self.driver.find_element(By.XPATH,
                                 "//div[@id=\'__next\']/div[2]/div/div/div[2]/div/div/form/div/div[2]/button").click()
        # 8 | click | linkText=See Plan Details |
        self.driver.find_element(By.LINK_TEXT, "See Plan Details").click()
        self.driver.implicitly_wait(60)


        @allure.step(title='open plan detail page')
        # 9 | verifyElementPresent | linkText=« Back to Medicare Advantage Plans |
        elements = self.driver.find_elements(By.LINK_TEXT, "« Back to Medicare Advantage Plans")
        assert len(elements) > 0
        sectionCount = self.driver.find_elements(By.XPATH, "//div[@id=\'__next\']/div[3]/div[5]/div/div")
        # print("sectionCount is", len(sectionCount))

        count = len(sectionCount)
        for i in range(count):
            j = str(i + 1)
            df_obj.iloc[i, 4] = self.driver.find_element(By.XPATH,
                                                         "//div[@id=\'__next\']/div[3]/div[5]/div/div[" + j + "]/div/div").text
            df_obj.iloc[i, 5] = self.driver.find_element(By.XPATH,
                                                         "//div[@id=\'__next\']/div[3]/div[5]/div/div[" + j + "]/div/div[2]/strong").text
        df_obj.to_csv(filename, index=False)



if __name__ == '__main__':
    newMedicare = TestMedicarePlanDetail()
    newMedicare.setup_method("chrome")
    newMedicare.test_medicare()
    newMedicare.teardown_method("chrome")
    now = time.strftime("%Y-%m-%d-%H_%M_%S", time.localtime(time.time()))
    pytest.main("-s -q test_comparePlanDetail.py  --alluredir report-{0}".format(now))