# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
  

class testMedicareCensus():
    def setup_method(self, method):
        self.driver = webdriver.Chrome(executable_path='../../driver/chromedriver')
        self.vars = {}

    # def teardown_method(self, method):
    #     self.driver.quit()

    def test_medicareCensus(self):
        self.driver.get("https://sunmaker.medicare.healthinsurance.com/census")
        self.driver.set_window_size(1440, 900)
        self.driver.find_element(By.NAME, "census.location.zip").click()
        self.driver.find_element(By.NAME, "census.location.zip").send_keys("30301")
        # self.driver.
        self.driver.find_element(By.CSS_SELECTOR, ".sc-1fn8n0v-1").click()
        self.driver.find_element(By.LINK_TEXT, "See Plan Details").click()